[package]
name = "Lean4TuringMachine"
version = "0.1"
lean_version = "leanprover/lean4:nightly-2021-11-05"

[dependencies]
AxiomaticSystem = {git = "https://github.com/cogrpar/AxiomaticSystem/", rev = "7986059c3c5dc8111e46324f9c43d5b0b673d4b6"}